### ISSUE TITLE
Replace freetype-freeworld with fontconfig-ultimate to improve font rendering

### ISSUE THREAD

**Issue by p-e-w** [folkswithhats/fedy#149]
https://github.com/bohoomil/fontconfig-ultimate gives what looks like the best font rendering on any platform, beating Ubuntu and even OS X. It's also very actively developed and maintained.

I realize there are no official Fedora packages at the moment, but maybe the author is willing to help set this up. Since for most Fedora users, the first step after installing is to get fedy, both projects could get a boost if fedy brought the "world's best font rendering" within a click's reach.

**Comment by satya164** [comment]
The problem with infinality or other solutions like this are that they aren't properly maintained. Currently we're using a custom config with freetype from the Ozon repo.

I would like to talk to @bohoomil and see if we could include this in the Ozon repo.

**Comment by bohoomil** [comment]
> properly maintained

What do you mean in particular?

> if we could include this in the Ozon repo

Sure. :-)

**Comment by satya164** [comment]
@bohoomil I meant, take infinality for example. They don't update their repo and as a result Fedy is broken.

Anyways, about including this in the Ozon repo, do you have Telegram/Hangouts? So that we could discuss it with our team?

**Comment by bohoomil** [comment]
@satya164 I'm sorry, but who are those "they"? I've maintained all Infinality resources for approximately three recent years, all the components are updated on a regular basis and are used in multiple distributions, both mainstream and smaller ones. I don't release binary packages for anything but Arch Linux, but packages for RH/Fedora, OpenSUSE, Debian/Ubuntu and many others exist. Besides, if you roll your own distro creating a couple of custom libraries from ready to use resources shouldn't be a big deal.

Take a look at the [project's site](http://bohoomil.com) and the [G+](http://plus.google.com/+bohoomil-infinality-bundle/) account for additional info and contact information.

**Comment by satya164** [comment]
@bohoomil Oh. I wasn't aware :). The problem was that the infinality repo is not updated as soon as new versions of fedora release. Though I understand, it means people will complain that Fedy doesn't work for that amount of time.

That's why I want to include this in our repo, so we could update as soon as new Fedora releases happen. Cheers!

**Comment by zmnp** [comment]
Hello, do you have plans to include infinality bundle (& fonts) to fedy?

**Comment by Abhinav1217** [comment]
Any status on this issue?

**Comment by DStewart1997** [comment]
[This](https://danielrenninghoff.com/2015/11/22/infinality-ultimate-bundle-packaged-for-fedora/) is worth looking into.

**Comment by Abhinav1217** [comment]
Read the post. but as @satya164 said above, infinality repo is not updated as soon as new fedora is released. Thus it would break fedy if used. The post is of Nov 22 and disclaimer mentions software is beta, so it can't be used with fedy. 

Best middle path seems that we incorporate methods from @bohoomil implementation into our own fedy-font-config , or contact him and offer help in maintaining fedora repos for infinity font config

**Comment by bddenhartog** [comment]
@Abhinav1217 @satya164 @bohoomil Is there an update on this? I'm going through the older issues and trying to ascertain what can/should be closed or not.

**Comment by bheru27** [comment]
I could setup a copr repo (with some help because i dont know how to do it) but im willing to maintain it

**Comment by bheru27** [comment]
Wops, sorry

**Comment by Abhinav1217** [comment]
@bddenhartog We were kind of stuck with this because of _is it needed anymore or not_ situation. Our font-config, although is old script, works really great. We do incorporate lots of technique from fontconfig ultimatium but at that time, we could not depend on infinality repos.

This issue was added during F20-21 era when gnome changed a lot of things daily and fedora in its default, had issues with rendering fonts and all things other. Now, in F25, on my laptop, The difference in, before and after, implementing fedy-font-config is unnoticeable. There was a slight improvement on my desktop but still unnoticeable .

@bheru27 There is no need for copr as far as I think. https://github.com/folkswithhats/fedy-packaging/blob/master/SPECS/fedy-font-config.spec is the file with configuration. You can adjust configurations there. We can install more fonts using that spec itself. I have been thinking about installing `source code pro`, and `google roboto` fonts, because I have been using it personally as global fonts. 

Maybe we could review https://github.com/folkswithhats/fedy-packaging/blob/master/SPECS/fedy-font-config.spec if it is in need of any update or not. We can close this because Fedora is improving its rendering with every release.
