### ISSUE TITLE
Suggestion: replace outdated Adobe Flash with Pepper Flash

### ISSUE THREAD

**Issue by procedural** [folkswithhats/fedy#212]
Adobe Flash is outdated, slow and buggy. Also, it's officially discontinued.

Recently I stumbled upon this version of Flash called Pepper Flash Player, from [debian website](https://wiki.debian.org/PepperFlashPlayer):

"Pepper Flash Player is maintained by Google, and is newer than Adobe Flash Player. Adobe currently still provides security fixes for Adobe Flash Player. Google provides newer features in Pepper Flash Player. Pepper Flash Player can currently only be used with Chromium (and with Chrome)."

And it's possible to make it work for Firefox too, just a matter of installing Fresh Player Plugin.

Here's working commands for Fedora 22:

```bash
sudo dnf install -y --nogpgcheck http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm
sudo dnf install -y chromium-pepper-flash freshplayerplugin
```

I've tested it already on FIrefox 38 and it's much faster than Adobe Flash.

**Comment by Rohan62442** [comment]
I'd suggest offering it as a separate plugin instead of replacing Adobe Flash. At least until Adobe keeps providing security updates to Adobe Flash

**Comment by procedural** [comment]
@Rohan62442 Yea, that's an option too. Poor people who choose Adobe version though, it may bring confusion to people which version they'll pick, the slow horrible one or the one that works.

**Comment by andreicristianpetcu** [comment]
Can there be two separate options? Adobe Flash and Adobe Pepper Flash

**Comment by procedural** [comment]
@andreicristianpetcu sure, why not.

**Comment by hyphone** [comment]
The Freshplayer wrapper for Firefox is probably less secure because it isn't secured by the browsers sandbox. It's still to be considered as experimental.
The old Adobe Flash player also utilizes vdpau and does not use much of the CPU.
Please don't mix the Pepper Flash player with the Freshplayer wrapper :)

**Comment by sb56637** [comment]
@andreicristianpetcu 
> Can there be two separate options? Adobe Flash and Adobe Pepper Flash

Sounds good to me!

**Comment by procedural** [comment]
@Abhinav1217 care to explain?

**Comment by Abhinav1217** [comment]
@procedural To sum up. Separate plugins for both flash will be an option. But first, plugin system is being restructured for smoother resolution of such issues in future.  Currently Fedy now shows the licenses, i.e  Adobe is shown as propriety application. 

I explained same thing on a duplicate issue here, I was going to paste the answer here too before closing. I forgot it and closed it directly. Sorry for confusion. 

Current release was focused on migration from ozon repos to folkswithhats repo. Next few release will focus on this area.

**Comment by citizen-anon-x** [comment]
Why use an old outdated version?

**Comment by Abhinav1217** [comment]
What outdated version? Adobe has finally decided to maintain flash plugins for linux once again. I now have flash 24.xx for both flash-player and flash-plugin. one was installed with fedy, other was installed by command. But repo for both is same one which was installed by fedy

I was an absentee, for current release, this release is pushed by @bheru27 . Because of my absence, he had to push fedy quickly without updating all the plugins. 

Since adobe hadn't updated flash player for long time, we forgot about it. We will update the script by next release.
