### ISSUE TITLE
GRUB2 config fail on EFI system.

### ISSUE THREAD

**Issue by Abhinav1217** [folkswithhats/fedy#213]
Even though your script `grub2.plugin/setup.sh` handles the condition for EFI system or normal system. It is updating the normal grub entry instead of EFI grub entries. I have checked the paths of EFI file which is correct. I added `echo "normal user"` and `echo "EFI user` in your script and found that it is updating the `/boot/grub2/grub.cfg` file not the EFI file.

```
[Abhinav@abhinav-fed22 grub2.plugin] $ fedy
normal grub user
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.0.4-303.fc22.x86_64
Found initrd image: /boot/initramfs-4.0.4-303.fc22.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-4e0a848a85cf4e319ca2ff259f48bb84
Found initrd image: /boot/initramfs-0-rescue-4e0a848a85cf4e319ca2ff259f48bb84.img
done

``` 

Maybe if it checked for EFI file first, it would be better as non-efi system will never have /boot/efi/EFI/fedora path but EFI might still have old /boot/grub2 path

**Comment by egriffith** [comment]
I was about to submit an issue about this when I saw that there was already one created. 

The grub2 plugin only checks for whether /boot/grub2/ exists, this is incorrect as even a UEFI system will have the /boot/grub2/ directory, it will just be pretty sparse. 

If you hadn't already messed this up then the correct solution would be to just change to checking for whether /boot/grub2/grub.cfg exists. If it doesn't exist then youre on a UEFI system, if it does you're on a legacy system... but since Fedy has been out for months and doing this incorrectly then even on UEFI systems /boot/grub2/grub.cfg will exist since previous versions of fedy existed. 

Only safe solution now is to swap the conditionals and first check for the existence of the EFI directory. This directory will not exist on a legacy system, only on a UEFI system. If it doesn't check THEN move onto to checking for /boot/grub2/grub.cfg.

**Comment by satya164** [comment]
@egriffith Thanks. Will do.
