### ISSUE TITLE
fedy-installer errors on Fedora 21

### ISSUE THREAD

**Issue by dchicks-sensus** [folkswithhats/fedy#331]
I realize that Fedora 21 isn't the current release, but for those of us that don't care for the new neutered version of KDE, 21 is the release to be on.  I had Fedy working on it before, but I was forced to do a reinstallation due to a disk problem.  Anywho...when I try to run fedy-installer, I get the following error:

Status code: 404 for http://folkswithhats.org/repo/21/RPMS/noarch/folkswithhats-release-1.0.1-1.fc21.noarch.rpm

I am inferring that this means there it no longer support for Fedora 21?  I hope I'm wrong.
Any hope for me?
Thanks,
Dave

**Comment by Abhinav1217** [comment]
Fedy repo for F21 was removed in last week update  because fedora ended support for F21 quite some time ago.  You can still clone the github repo and build it on your system.  

Most of the plugins have been moved to https://github.com/folkswithhats/fedy-plugins-developers so download what you need and add them plugin folder.   Plugins can also be added in `~/.local/share/fedy/plugin` folder.

**Comment by dchicks-sensus** [comment]
Very well.  I figured it was something like that.  Thanks for the info.
