### ISSUE TITLE
Please provide download through HTTPS and stop encouraging users to do insecure stuff

### ISSUE THREAD

**Issue by genodeftest** [folkswithhats/fedy#362]
Currently on http://folkswithhats.org/, users are encouraged to download an unsigned file from an insecure connection and pipe it into their bash. This is horribly insecure for many different reasons. To name a few:

1. Users cannot know whether this code is valid. A hint for reading through the code would be useful.

2. Users cannot know whether the code was manipulated on the website or while being transmitted. Please make your website HTTPS-only and provide a PGP signature for your files.

3. Piping code from the internet into bash is insecure. Please don't suggest users to do that.

How about creating a package for official fedora repositories instead?

**Comment by Abhinav1217** [comment]
Official fedora repositories is not possible as it breaks the guidelines by providing softwares which fedora does not want to ship.

`HTTPS` was active until about a week ago when the certificate was expired. I haven't found time to renew it yet. But I will renew it soon. Since we are not earning money from fedy, I am using [letsencrypt](https://letsencrypt.org/) which provides free certificates which needs to be renewed every 3 months. I will renew it during upcoming release and automate it for the future to avoid expiration.

Code, Plugins, website and installer scripts are open source and hosted on github. Anyone can view it and contribute to it. Link to repo is provided on the website.  On your suggestion we will update the website to make it more clear to users.

One line command to install stuffs are quite common on linux packages. Fedy is aimed for ease of use, thus emphasis on it.  On your recommendation, we will mention on the website link to script, similar to rvm or nvm website.

Thank you for valuable suggestions, we will implement them one by one and improve the experience of using fedy.
