### ISSUE TITLE
Please stop downloading unsigned code or data from insecure connections

### ISSUE THREAD

**Issue by genodeftest** [folkswithhats/fedy#363]
Currently, for many plugins, fedy is downloading unsigned code or data (e.g. .repo files) from insecure (i.e. non-HTTPS) connections. This is bad because any attacker can easily perform a man-in-the-middle-attack on most users, especially those using wifi.

To add at least some minimal effort to hack your user's computers, please take these measures:
* use downloads through HTTPS where possible
* download signatures and verify them against known PGP keys with a known (trusted) trust chain

If you can't do both, please warn users that what they're doing is insecure. If you can't do any of these points, please don't even try, you are putting your users at risk!

Please note that with packages provided to dnf on its command line, PGP signatures are not checked.

**Comment by Abhinav1217** [comment]
Most of the application plugins are simple DNF commands which uses copr to install applications. Not all copr provide PGP signature. Many applications are also providing repos on simple http instead of https. We can't do anything about it. Even if you don't use fedy, you will be downloading those apps with insecure http connection from their website. Not everyone has updated their websites as https only. 

Having said that, those which do provide, we use HTTPS for all their downloads.  Just look at the regex scripts of vivaldi or jetbrains apps, or sublime text.  Our regex look for https connection along with http connection.
