### ISSUE TITLE
Create a plugin for Docker

### ISSUE THREAD

**Issue by bddenhartog** [folkswithhats/fedy#402]
With the new addition of the _Developers_ category (added in #401), creating plugins for development tools like Docker becomes easy to incorporate in this repository.

Initial request for Docker support in #394 by @metabsd. This issue was created to facilitate the addition of Docker individually, which makes for more concise pull requests (and issues!).

**Comment by Abhinav1217** [comment]
I will release F25 update of Fedy by 14th November. That release will get lots of "_can't install_" issues because of delays in 3rd party updating their links. I will release another update around 20 to 25th november to stabilize all that. 

After that I will work on your re-structuring idea. I was suppose to make a API oriented website to make all this easier but I got lazy overtime and it got stuck in limbo. I also need to update fedy app itself. If you can work with GJS and want to share load, let me know.

**Comment by bddenhartog** [comment]
@Abhinav1217 I'd be happy to help with development when possible. Let me know how to best work with you.
