### ISSUE TITLE
Remove the Permissive SELinux tweak

### ISSUE THREAD

**Issue by brortao** [folkswithhats/fedy#403]
For most people, setting SELinux to permissive is a bad idea. If there's a problem with a single application, it's much better to create a policy to get around that rather than compromising your computer's security through permissive mode. In general, SELinux doesn't cause nearly the amount of trouble for normal users that it once did, so disabling it is rarely justified.

There might be a few people who really do need to disable SELinux in some way or another, but if it's that important they'll already know how to. Having the option in Fedy only encourages unsafe behaviour.

**Comment by Abhinav1217** [comment]
Fedy is aimed to be simple enough for regular users of fedora. For most setting it to permissive is convenience. We don't disable it because that is a big security concern. Setting it to permissive is a good option which is both safe and secure for general usage. Permissive mode does not compromise the security of whole computer like you wrote.
For those who are above regular user, like devs, admins, Who are good with terminal command and rooting out daily issues, they can choose to ignore this tweak.  I personally ignored it on my work system but have enabled it at home. 

Fedy does not encourage unsafe behaviour. It has helped those new to linux adopt.
