### ISSUE TITLE
Fails to install themes

### ISSUE THREAD

**Issue by bheru27** [folkswithhats/fedy#407]
When i try to install this user theme, fedora cant find the packages, repo is probably dead. 
log:
"Failed to synchronize cache for repo 'user501254-Paper', disabling.
Last metadata expiration check: 1:29:49 ago on Thu Dec  8 17:50:21 2016.
No package paper-gtk-theme available.
No package paper-icon-theme available.
Error: Unable to find a match.
"

I guess we should start looking at the plugin to check where it gets the theme

-----------------
Edited, it happens with lots of other themes, it should be fixed asap

**Comment by e-inquirer** [comment]
Same here; themes don't install. Via Gnome notifications:

```
Task Failed
Paper themes (Install) failed.
```
Also, EvoPop and Numix missing from list.

**Comment by bertrandbo** [comment]
Hi,

Fedy relies on copr repositories to provide these themes.

Paper has not been built for Fedora 25. But, as I said in #392, it is available on another [copr](https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/). I'll propose a PR.

Numix is not maintained anymore on copr because it is now [in Fedora official repositories](https://github.com/numixproject/numix-specs). I'll also propose a PR.

As for EvoPop, I just cannot find any other maintained copr.

**Comment by simonsaysthis** [comment]
I can reproduce this bug on my system. Currently the only theme which is working is Numix

**Comment by bheru27** [comment]
That's my fault, i didnt remove the non working  themes in the new build, i was working on getting the other repos from github, or how to compile/install them, i might start a copr repo for it.

**Comment by Abhinav1217** [comment]
Evopop and arc theme from copr is not yet built for F25.

 @bheru27 I have already started updating the plugins, I will upload them after testing. Since I did a clean format, I will have to create new set of VMs for testing, so it will take some time before I push a PR.  Here are the links i am using if you want to work with it.
 
Solus has reworked on [evopop theme ](https://github.com/solus-project/evopop-gtk-theme/) but it logs lot of  [deprication issues](https://github.com/solus-project/evopop-gtk-theme/issues/66)  when launching gui from Command line. 

Older evopop gtk theme is still working on F25 but new elements are missing. Old repo is now removed from github, I happened to have it in my backup. If you want it I will add it to github.

Old evopop icon theme is [here](https://github.com/solus-cold-storage/evopop-icon-theme). 

I found a rebooted ozon icon theme at https://github.com/digitalgutenberg/ozon-rebooted-icon-theme
Ozon gtk theme is crashing, I couldn't find a working updated repo yet.
 
I found working Ozon shell theme in [blue](https://github.com/DreadedX/ozon-blue-shell) and [red](https://github.com/sboli/ozon-shell-theme) version. I would really like to give them rebirth. Anyone knows how to build shell themes and is interested, please contribute.

https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/ have most updated collection of themes, Original fedy plugins are using it. It has both arc theme and paper theme. I couldn't find the non-transparent version for arc yet.

**Comment by satya164** [comment]
@Abhinav1217 I believe Numix themes are in official fedora repos now.

**Comment by Abhinav1217** [comment]
Great. So numix in fedora repos are fully updated one. 
What about ozon themes, will you work on updating them.  I am interested in rebooting them in folkswithhats organization. If you or someone could provide some build instructions, maybe we can revive them. Now since gnome-shell guys has said they won't have breaking changes every release, it should be a bit easier to maintain now.

**Comment by satya164** [comment]
@Abhinav1217 Ozon is abandoned. I'm not planning to work on it anymore and I don't know anyone else who does. If someone wants to take over, I'm happy to provide build instructions.

**Comment by Abhinav1217** [comment]
Please provide build instruction ( detailed one if possible ) and let us revive the themes under folkswithhats banner. We can think of a different name if using Ozon is not possible.

**Comment by Abhinav1217** [comment]
@bheru27 Have you updated the plugins with new links?

**Comment by satya164** [comment]
Build instructions are in the README in the repo. It's nothing complicated. Let me know if it doesn't work.

Using the name Ozon shouldn't be a problem, but it's better to talk to @Foggalong if you want to use the name.

**Comment by bheru27** [comment]
No I havent, let me rebuild everything now

**Comment by bddenhartog** [comment]
@bheru27 can I get a status update?

**Comment by bheru27** [comment]
What? @bddenhartog ? I did a new build yesterday, update your repos

**Comment by bddenhartog** [comment]
I changed the label to `bug (confirmed)` simply because the `bug` label was on it before (which was changed to `bug (unconfirmed)`. Thanks for reminding me that this should be closed!

**Comment by Foggalong** [comment]
@Abhinav1217 

Originally when Ozon merged into Korora the idea was that at some unspecified point in the future the theme suite would ship was default in their distro. This largely relied on me having time to bring the icon theme up to scratch and making sure the GTK theme worked with the latest version (which in turn depended on me learning how GTK theming works). Since then things have happened in my life which have meant I've been unable to give this the time it needs.

If you're wanting to reboot it then I'm happy to add you into the Ozon organization so that you can continue it using the official repos and the official name. Alternatively if you wanted to do it with the backing of a larger project then it could be migrated and done within Numix or I could talk to the Korora guys about doing it there.

**Comment by Abhinav1217** [comment]
@Foggalong 

Hi, Sorry it took me so long to see this. Just two nights ago, I was thinking about how to reboot a fork of Ozon and original evopop theme here under folkswithhats. Lack of resource on GTK theming is a big demotivator. Most of the stuff I find is quite old. Using Adwaita theme as a reference is really a bad choice but I can't see any other option.

Can we do it here under FWH? It would be simpler for me to keep track of stuffs. 

A *disclaimer*, Though I am a fan of ozon, and want to bring it to live ( I am actually using ozon blue theme now ). But I am not a designer at all. I just hope that once I update it to 3.22, it will start attracting contributors, and we can keep it running.

Hope you and the guys at Korora and Numix are ok with this.

**Comment by satya164** [comment]
> Can we do it here under FWH? It would be simpler for me to keep track of stuffs.

I think it'd make more sense under numix organization

**Comment by Abhinav1217** [comment]
If you think so. I was just thinking FWH should have more than just fedy. That was the reason for you to choose new name, remember.

**Comment by Foggalong** [comment]
@Abhinav1217 It might just be me, but it feel kinda weird that a theme suite and a repository/package installation application would be maintained under the same org. They're very different projects

**Comment by satya164** [comment]
@Abhinav1217 we chose a new name so that we could have more software/tools etc. I think numix is more suitable for a theme. there are already theme developers and cotributors in numix. so ozon will be more benefited from being under numix than fedy. it might just die eventually under folkswithhats.

**Comment by Abhinav1217** [comment]
You are right. Ozon or Numix it is. I have Ozon shell theme in red and blue theme. And a version of original evopop gtk theme ( one which had colored buttons for max,min,close ) slightly updated to have better file progress dialog in nautilus.  Ozon icon theme works well, I don't know if there is any need for update.

**Comment by Foggalong** [comment]
@Abhinav1217 Icon theme was originally set up to be mostly used for apps which were already on the system, so is missing a lot of symlinks for things that aren't.

**Comment by user501254** [comment]
@bheru27 
I had to manually set the Copr build Setting to build for Fedora 25. However I have made some changes so that this won't happen in the future.
I try to keep the packages as up to date as possible but in case you are wondering, there have been no updates to the [paper-gtk-theme](https://github.com/snwh/paper-gtk-theme) repo in some time now.
If there are any issue with the packages you can report them [here](https://github.com/user501254/packaging/issues).

**Comment by user501254** [comment]
```

Copr repo for Paper owned by user501254                                  18 kB/s | 153 kB     00:08    
Last metadata expiration check: 0:00:08 ago on Sat May 13 01:55:32 2017.
Dependencies resolved.
========================================================================================================
 Package               Arch        Version                                  Repository             Size
========================================================================================================
Installing:
 gtk2-engines          x86_64      2.20.2-11.fc24                           fedora                311 k
 paper-gtk-theme       noarch      2.1.0-0.265.20160501gitf75724f.fc25      user501254-Paper      698 k
 paper-icon-theme      noarch      1.4.0-0.679.20160501git579e9aa.fc25      user501254-Paper       43 M

Transaction Summary
========================================================================================================
Install  3 Packages

Total size: 44 M
Total download size: 43 M
Installed size: 58 M
Downloading Packages:
[SKIPPED] gtk2-engines-2.20.2-11.fc24.x86_64.rpm: Already downloaded                                   
(2/3): paper-gtk-theme-2.1.0-0.265.20160501gitf75724f.fc25.noarch.rpm    67 kB/s | 698 kB     00:10    
(3/3): paper-icon-theme-1.4.0-0.679.20160501git579e9aa.fc25.noarch.rpm  107 kB/s |  43 MB     06:48    
--------------------------------------------------------------------------------------------------------
Total                                                                   108 kB/s |  43 MB     06:48     

Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction

```
