### ISSUE TITLE
Fix uninstallation scripts using rm to remove files/directories

### ISSUE THREAD

**Issue by bddenhartog** [folkswithhats/fedy#426]
# Description

In some uninstall scripts/commands for various plugins, `rm [options] /path/to/whatever` is used to remove files or directories added when installing the plugin. This sometimes causes an additional prompt asking the user to confirm the removal of the file/directory, and then uninstallation of the plugin would fail.

We first saw this reported in the discussion of PR #393, by @danstewart. I'm happy to report that I've found the issue!

On some systems, the `root` user has a bash runcom (`.bashrc`) with a few aliases defined. Here's the output of `sudo cat /root/.bashrc` on a fresh F25 installation:

```bash
$ sudo cat /root/.bashrc
> # .bashrc
>
> # User specific aliases and functions
>
> alias rm='rm -i'
> alias cp='cp -i'
> alias mv='mv -i'
>
> # Source global definitions
> if [ -f /etc/bashrc ]; then
>	. /etc/bashrc
> fi
```

The issue is caused by the alias of `rm` to `rm -i` -- the `-i` flag adds a prompt before every removal (same goes for the `alias cp` and `alias mv` definitions.) Our `run-as-root` script causes the commands to be ran as the root user, which of course loads the `.bashrc` containing the offending alias.

I'm sure Fedora chose to implement this as an additional gate to preventing accidental file modifications. Thankfully, the solution is pretty simple.

# Task Details

- Call `unalias` for `rm`, `cp`, and `mv` inside `bin/run-as-root` prior to executing the arguments.
- Ensure that no usages of `rm` are passing the `-i` flag manually

That's it!

**Comment by satya164** [comment]
I'm thinking if it's possible to override the alias instead of having to change all scripts

**Comment by bddenhartog** [comment]
> I'm thinking if it's possible to override the alias instead of having to change all scripts

Yes, but it would be cleaner to simply use the full path to the binary. Overriding the alias seems hacky.

**Comment by satya164** [comment]
Don't think so. You've to remember to do it in every script. Overriding the alias once in `run-as-root` is much simpler.

**Comment by satya164** [comment]
I think it boils down to this, unaliasing is very simple fix without any downsides (?). why do you think it's hacky? changing every script is a much more invasive change. I'd always go for the simpler fix as long as it doesn't have any downsides.

**Comment by bddenhartog** [comment]
IMO, the full path is what should have been used in the first place. Not doing so is why the alias causes issues for us in the first place. 

Overriding it creates additional code that we need to maintain, and who knows if it will always be necessary - say the alias is removed in a future version of Fedora, we would then have unnecessary cruft. 

I see it just like aliasing imports in other programming languages. Sure, you can `import UserProfile as prof`, but then if you refactoring `UserProfile` to `CustomerInfo` your `prof` alias stops making sense and becomes cruft that simply exists to make it slightly more complex for new developers to step through stuff in that file. Perhaps a contrived example, but I think you can get the drift.

**Comment by satya164** [comment]
> IMO, the full path is what should have been used in the first place. 

Why? Use `/usr/bin/wget` for `wget`, `/usr/bin/dnf` for `dnf`? Doesn't feel right. That's why the OS provides abstractions over them `PATH` and aliases, let's use them.

> Overriding it creates additional code that we need to maintain, and who knows if it will always be necessary - say the alias is removed in a future version of Fedora, we would then have unnecessary cruft.

It's one line of very simple code and hardly adds any maintenance cost. Using absolute path everywhere however, adds complexity to individual plugins because now each of the plugins have to be aware that `rm` is actually an alias and they need to use absolute path, contrary to the usual way.

It's the same reason the `run-as-root` abstraction exists instead of requiring plugins to use policy kit directly.

> I see it just like aliasing imports in other programming languages. Sure, you can import UserProfile as prof, but then if you refactoring UserProfile to CustomerInfo your prof alias stops making sense and becomes cruft that simply exists to make it slightly more complex for new developers to step through stuff in that file. Perhaps a contrived example, but I think you can get the drift.

It's nothing like aliasing a variable/import to another one. You're changing the behaviour as opposed to just aliasing something. It's more like a polyfill. For example say the behaviour of the global `Promise` object doesn't match the standard behaviour in a browser. So what do you do? You replace it with a custom implementation which implements standard behaviour. Now, sometime in future, the browser will implement the standard behaviour. Now you can just get rid of the polyfill, without touching your existing code. There's another way, that is to go around changing your code everywhere, so instead of doing `new Promise()` you `import StandardPromise` and then do `new StandardPromise()`. Now in future browser has the standard promise behaviour implemented. So you go around changing your code again to `new Promise()`.

You don't avoid abstraction because in future you might not need it in future. Quite the opposite, because in future when you don't need the complex implementation anymore, you can replace it with a simpler implementation without having to touch anything else.

**Comment by bddenhartog** [comment]
I totally understand where you are coming from; it's just that I see the shorthand usage of `rm` as the alias to be removed (or, to match your example, polyfill.)

That's probably just a byproduct of my shell scripting experience, where full paths to binaries are often preferred, since the user can override what `rm` does but not `/usr/bin/rm` -- using the full paths to binaries while writing cross-distro scripts is useful, because you avoid potential side effects that cause unexpected behavior (like the issue we have with `run-as-root` and `rm`.) And yes - personally I'd prefer if all binaries were called directly, for the exact reason I just described.

There actually wouldn't be a need to change them back in the future; that's what my proposed solution ensures. `/usr/bin/rm` will always point to the binary and won't ever require modification. I can agree that because of the unique need for this in the project, and the fact that we do not enforce all binaries are used the same way, that it could potentially cause review overhead.

**Comment by satya164** [comment]
Even if you don't remove it in future, what's the downside of just overriding it as opposed to introducing additional maintenance overhead, i.e. requiring all plugins to know about the implementation detail that behaviour of `rm` is different and requiring extra work to ensure every plugin does it during PR review?

I don't see why unaliasing shouldn't be the preferred solution, given the downsides of using absolute paths, whereas there are no downsides I know of when unaliasing.

**Comment by bddenhartog** [comment]
Fair point, and as I mentioned, I can see how it would increase difficulty for contributors/reviewers because we don't enforce that all binaries are called with the full path. I'll update the task description.

**Comment by Abhinav1217** [comment]
Any work done on this @bddenhartog ?

**Comment by Abhinav1217** [comment]
Changing Lable from plugin to core as it is convenient to add unalias in the core than to change all the plugin scripts.

**Comment by bddenhartog** [comment]
Whoops - your notifications went totally unnoticed and I've been wrapped up in other things. I'll get a PR out for this tonight.

**Comment by bddenhartog** [comment]
So I did some testing the other day, and can't seem to replicate this issue. I had @danstewart try the removal of the `-i` flag, and that didn't seem to solve the issue he experienced when this was originally surfaced. Closing this issue for now as it cannot be recreated in a fresh installation of Fedora 25.
