### ISSUE TITLE
Network timeout. folkswithhats.org

### ISSUE THREAD

**Issue by 412andrewmortimer** [folkswithhats/fedy#434]
Trying to curl, as per the one-liner on http://folkswithhats.org/ or trying to manually accomplish the tasks of the installer failure is reached due to network timeout.

Using Fedora 25. Can provide other details if asked.

~~~
rpm --quiet --query folkswithhats-release || dnf -y --nogpgcheck install https://folkswithhats.org/repo/$(rpm -E %fedora)/RPMS/noarch/folkswithhats-release-1.0.1-1.fc$(rpm -E %fedora).noarch.rpm

~~~
~~~
Last metadata expiration check: 0:02:42 ago on Thu Mar  2 11:47:16 2017.
Curl error (28): Timeout was reached for https://folkswithhats.org/repo/25/RPMS/noarch/folkswithhats-release-1.0.1-1.fc25.noarch.rpm [Connection timed out after 120001 milliseconds]
~~~

**Comment by bddenhartog** [comment]
@412andrewmortimer Looks like it is currently down. We're investigating and will report back when we have more information.

In the mean time, if you'd like to use Fedy, I'd recommend running the commands within the installation for each plugin you need manually. You can get this by looking at the `install.sh` script in each plugin's directory, e.g. `/plugins/{plugin_name}/install.sh`.

**Comment by 412andrewmortimer** [comment]
Thank you! I'll be checking back for sure. Thank you for providing alternatives for the meantime. I appreciate it.

 :smile:

**Comment by bddenhartog** [comment]
The website has been down due to an issue caused at the provider's level. Plans are in place to migrate the website to a more stable environment this evening (a few hours from now).

We apologize for any issues this may have caused anyone. Using `curl | sudo sh` to access the scripts directly from this repository (as shown [in a previous comment](https://github.com/folkswithhats/fedy/issues/434#issuecomment-283712931)) should be a successful workaround for anyone who wants to run the same exact commands that the GUI application runs.

**Comment by bddenhartog** [comment]
Sorry for the delay, I fell asleep. Site is up and running in a more stable environment; we shouldn't have any significant downtime in the future.

**Comment by AlexandreDecan** [comment]
Could you please confirm that https://www.folkswithhats.org/repo/25/RPMS/noarch/folkswithhats-release-1.0.1-1.fc25.noarch.rpm is supposed to be available right now? Because I'm getting a 404 status code...

**Comment by AlexandreDecan** [comment]
Oh, and while I can access to the website, downloading the installer lead to having ``fedy-installer`` contains the following:

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.8</center>
</body>
</html>
```

One possible explanation is that you updated the DNS of folkswithhats.org... if so, I just have to wait a bit ;)

**Comment by bddenhartog** [comment]
@AlexandreDecan

> Could you please confirm that https://www.folkswithhats.org/repo/25/RPMS/noarch/folkswithhats-release-1.0.1-1.fc25.noarch.rpm is supposed to be available right now? Because I'm getting a 404 status code...

Oops! I took over hosting the website, and wasn't aware that the repositories should have been bundled with those (maybe I should have looked at `fedy-installer`... `>_<`).

The RPMs are now available.

> Oh, and while I can access to the website, downloading the installer lead to having ``fedy-installer`` contains the following:
> 
> ```
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body bgcolor="white">
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx/1.11.8</center>
> </body>
> </html>
> ```
> 
> One possible explanation is that you updated the DNS of folkswithhats.org... if so, I just have to wait a bit ;)

You're seeing this because you're trying to download the installer over `http` without following redirects. `https` is enforced across the website, as (to my knowledge) has been for some time. Both `curl` and `wget` provide ways to follow redirects if you _need_ to use `http`; otherwise, I'd recommend using the `https` path displayed on the index of the website.

**Comment by jonnjonzzn** [comment]
I'm getting this now:

"Failed to synchronize cache for repo 'folkswithhats', disabling."

**Comment by bddenhartog** [comment]
@jonnjonzzn Likely due caching of DNS/NS records on your workstation or on some host in between you and the server.

We changed the nameservers last night (about 24 hours ago), so changes should be propagated to most hosts. Are you able to try again in a few hours and let me know if it's working for you? I'm not having any connectivity issues here.

**Comment by bddenhartog** [comment]
@jonnjonzzn Try running `dnf clean all` and try updating again.

**Comment by AlexandreDecan** [comment]
> The RPMs are now available.

Indeed, I can download them now. Thank you!

> You're  seeing this because you're trying to download the installer over http without following redirects. https is enforced across the website, as (to my knowledge) has been for some time. Both curl and wget provide ways to follow redirects if you need to use http; otherwise, I'd recommend using the https path displayed on the index of the website.

I cut&pasted the command displayed on the website which leads to a syntax error (because of the HTML). Even when I try to manually download fedy-installer (both on https or http), I get the same file. 

> The domain's nameservers were updated, so if you receive periodic 404s while making requests to the website, try flushing your DNS cache.

I don't own any local DNS cache, and I assume this is not the problem, because folkswithhats.org is properly resolved. Could you please check that https://folkswithhats.org/fedy-installer is available, and not the (969Bytes sized) file that contains some HTML?

As a workaround, I took the one that is available on 
https://github.com/folkswithhats/folkswithhats.org/blob/master/fedy-installer
but I got the same error than @jonnjonzzn, even after running  ``dnf clean all``.

**Comment by satya164** [comment]
> I don't own any local DNS cache

Every system has a DNS cache - https://www.cyberciti.biz/faq/rhel-debian-ubuntu-flush-clear-dns-cache/

> Could you please check that https://folkswithhats.org/fedy-installer is available

I'm getting the correct file

**Comment by bddenhartog** [comment]
@AlexandreDecan 
> I **cut&pasted the command displayed on the website** which leads to a syntax error (because of the HTML). Even when I try to manually download fedy-installer (both on https or http), I get the same file.

Aha! That url is actually now incorrect and needs to be updated. All traffic (insecure, secure) is now forwarded to `https://www...`, which is different behavior from before. Adding the `-L` option to `curl` would allow you to follow the redirect and get the proper contents.

@AlexandreDecan 
> I got the same error than @jonnjonzzn, even after running `dnf clean all`.

Yeah, we're aware of this issue but don't have a fix right now. I'm able to recreate this locally, even upon restarts and `dnf clean all` / `dnf makecache` / `dnf update --refresh`. As a (not-so-great) workaround would be to install the `RPM`s directly; the tree can be viewed at https://www.folkswithhats.org/repo.

@satya164 
> Every system has a DNS cache

Yes, but not every system actually uses it. Ubuntu, for example, uses `dnsmasq`, but doesn't actually cache the data locally -- so the DNS caching happens at the ISP level, or whatever the DNS provider is (e.g. if the user is using Google's public DNS). I'm not 100% about Fedora's default behavior in this respect.

@satya164 
> I'm getting the correct file

That would only happen if you downloaded it by visiting the URL in your browser. `curl https://folkswithhats.org/fedy-installer`, without the option to follow redirects (`-L`), should give you the file that @AlexandreDecan is getting, with the 301 redirect notice.

**Comment by AlexandreDecan** [comment]
Thanks for the answers @bddenhartog !

> Aha! That url is actually now incorrect and needs to be updated. All traffic (insecure, secure) is now forwarded to https://www..., which is different behavior from before. Adding the -L option to curl would allow you to follow the redirect and get the proper contents.

Ok. While I understand why ``curl`` needs this extra parameter, I don't understand why my Firefox is not able to follow the redirection :) Btw, the ``fedy-installer`` available in the github repository made it for me (or at least, it solved this step ^^). Maybe you should consider updating the command-line on the website (either to add -L, or to adapt the URL)?

Oh, another tiny suggestion: maybe you should remove the "rm fedy-installer" on https://github.com/folkswithhats/folkswithhats.org/blob/master/fedy-installer#L23, unless the script succeed to install fedy. This could help people to retry the installation process without having to download the script again and again ;)

Another minor "issue": following what you said here above, I suggest to make use of https instead of http for /etc/yum.repos.d/folkswithhats.repo, see here: 
https://github.com/folkswithhats/fedy-packaging/blob/master/SPECS/folkswithhats-release.spec#L23

Given what you said about ``https://www...`` stuff, I tried to replace the ``baseurl`` with ``https://www.folkswithhats.org/repo/\$releasever/`` but that did not do the trick :( I'm still getting the "failed to synchronize cache for repo 'folkswithhats'". I

**Comment by bddenhartog** [comment]
@AlexandreDecan 

> Oh, another tiny suggestion: maybe you should remove the "rm fedy-installer" on https://github.com/folkswithhats/folkswithhats.org/blob/master/fedy-installer#L23, unless the script succeed to install fedy. This could help people to retry the installation process without having to download the script again and again ;)

I'll take a look at this, thanks for the suggestion. One issue I see with this is leaving garbage behind after installing, but I plan on refactoring the installation process pretty soon anyhow. Perhaps downloading to `/tmp` or otherwise avoiding deletion if a CLI argument (something like `--keep-installer`) is passed might be better solutions than what we're currently doing.

> Another minor "issue": following what you said here above, I suggest to make use of `https` instead of `http` for `/etc/yum.repos.d/folkswithhats.repo`, see here:
> https://github.com/folkswithhats/fedy-packaging/blob/master/SPECS/folkswithhats-release.spec#L23

Yup! This is known and will be fixed tonight. I ran out of time to follow up with some of the smaller changes that should have been made.

> Given what you said about `https://www...` stuff, I tried to replace the baseurl with `https://www.folkswithhats.org/repo/\$releasever/` but that did not do the trick :( I'm still getting the "failed to synchronize cache for repo 'folkswithhats'".

In my testing this morning, I experienced that too. `dnf` should be following the redirect successfully anyhow, but it is definitely odd that it can't synchronize.

**Comment by bddenhartog** [comment]
Actually, as I was typing that out I did some additional sanity checks and found the issue. I'll be able to apply the fix in about an hour and a half.

**Comment by bddenhartog** [comment]
The issue should be resolved now. Make sure you rebuild your metadata cache by executing `dnf makecache`. If you're still experiencing issues, leave a comment here.

**Comment by satya164** [comment]
> Oh, another tiny suggestion: maybe you should remove the "rm fedy-installer" 

We could change the instructions on the website so that it downloads the script in memory and executes rather than saving as a file. In that way be default no extra files are left and people can download the file if they want to without having to know extra CLI argument.

**Comment by AlexandreDecan** [comment]
thanks for the fix, @bddenhartog!
