### ISSUE TITLE
Install issue with script

### ISSUE THREAD

**Issue by ltelmo** [folkswithhats/fedy#436]
It sems the install script is borked at moment, It will not install cannot find items and fails

Thanks for the great item that lets me use Fedora!

**Comment by bddenhartog** [comment]
Can you provide any more details? Can you post the command you ran? The displayed command was recently updated to `curl | sudo bash`, if you didn't run that then clear your cache, refresh the page and try the displayed command again.

**Comment by ltelmo** [comment]
when coping and pasting the command to install Fedy from the webpage it starts asks for password and then fails do to unable to find which i cant quite remember repo or something then exits .
This started after Fedy was unreachable earlier in the week no when reinstalling on a new install of Fedora this is what is happening
Thankyou

**Comment by bddenhartog** [comment]
> when coping and pasting the command to install Fedy from the webpage it starts asks for password and then fails do to unable to find which i cant quite remember

This sounds like you ran the previous command that was displayed, something like `bash -c 'su -c "curl ..."'`. This command (which has since been removed from the website) invokes `su`, which (by default) assumes the identity of `root`. That's the password you were being asked for -- not your user's password.

This is all moot, of course, since the command has been updated to . You'll still be asked for a password, but it's your regular user password.

You should refresh `https://www.folkswithhats.org`, and run the new command displayed there.

> This started after Fedy was unreachable earlier in the week no when reinstalling on a new install of Fedora this is what is happening

This happened due to some networking issues. See #434 for more information.

**Comment by ltelmo** [comment]
okay thank you very much i see the web page has refreshed and changed, i wil try it
