### ISSUE TITLE
Caching/Updating question

### ISSUE THREAD

**Issue by xasx** [folkswithhats/fedy#471]
Hi there,

just a question:

Many plugins utilize a cache for downloaded files in order to speed up re-installs.

However, this prevents the re-install method to be used for updates since the files never get downloaded again unless the cache is wiped manually. Is there anything that I am missing regarding the cache or its cleanup? Are there perhaps plans to provide a dedicated 'Update'/'Install latest' button that just wipes the cache before installing again?

Thanks in advance & regards

**Comment by bddenhartog** [comment]
Caching is handled by `wget`, which respects the `Expires` HTTP header set by the server you are communicating with. This means that when files on remote servers change and the server's cache is reset, `wget` will download the new version.

**Comment by xasx** [comment]
@bddenhartog I was referring to the cache directories as defined e.g. in https://github.com/folkswithhats/fedy/blob/master/plugins/gitkraken.plugin/install.sh#L3

**Comment by bddenhartog** [comment]
@xasx Yes, I know. The "cache directory" `/var/cache/fedy` is simply convention. `wget` actually handles detecting "oh, we already downloaded this" - that's the reason that script changes to `/var/cache/fedy`.

**Comment by bddenhartog** [comment]
I feel like my last comment might be unclear. Here's the workflow, in a bulleted list:

- Change to /var/cache/fedy
- Download some-file-foo.tar.gz with wget
- Install...

Later, if the user removes the plugin and clicks "Install" again:

- Change to /var/cache/fedy
- Request to download some-file-foo.tar.gz with wget
   - wget detects that we have a file already at the given output location  (the `-O` switch, if provided; otherwise it's just the filename as it exists on the server)
    - wget checks the `Expires` HTTP header sent by the server, realizes that the expiration of the file hasn't been reached, and skips the download. If the expiration had been reached, however, it would have re-downloaded the file.

**Comment by xasx** [comment]
Thanks for clarification. Been confused lately… :wink:
