### ISSUE TITLE
Installation instructions shouldn't suggest users `curl | sudo bash` the script

### ISSUE THREAD

**Issue by mhsabbagh** [folkswithhats/fedy#476]
Hello.

On the official website of Fedy, you are suggesting to use curl as a root user in order to download the installer from the website and then run it. However, such method is dangerous for a lot of reasons, a simple example would be that the website may be compromised/domain expires/someone finds a way to get in; and the installer code could be modified. Infecting a lot of users.

Also, using curl with an online script as a root is not very much safe from users side. Even though the installer may not contain anything malicious, a lot of users wouldn't prefer such method. The code could be modified according to user agent for example.

Thus, I would like to suggest using normal dnf and rpm commands directly instead of the simple curl command installer. It won't be more than 2-3 lines in total.

**Comment by bddenhartog** [comment]
I agree with the sentiment that the current installation instructions normalizes running scripts from the internet as the super user, which is - generally speaking - a bad habit to form, however, it is incorrect to say that the installation script is _dangerous_.

The reason this was written in the past is because simply because it was fairly common; not that this justifies it, but I think it's fair to say that FWH isn't doing anything outrageous.

That said, I think it _is_ important that we refactor the installation. In folkswithhats/folkswithhats.org#8, @bugaevc [suggests that Fedy be packaged as a flatpack package](https://github.com/folkswithhats/folkswithhats.org/issues/8#issuecomment-285593372). This is one option; there are several others currently under consideration. 

There is just one more thing I'd like to address from your report:

> However, such method is dangerous for a lot of reasons, a simple example would be that the website may be compromised/domain expires/someone finds a way to get in; and the installer code could be modified. Infecting a lot of users.

If someone gains control of the domain name, or gains access to the server, the installation method doesn't matter - installing a bad rpm from a server that has been compromised is as equally potentially harmful as executing shell commands as the root user.
