### ISSUE TITLE
Build a Fedora 27 package

### ISSUE THREAD

**Issue by ycollet** [folkswithhats/fedy#552]
Fedora 27 is out today.

**Comment by luisnabais** [comment]
Actually it came out yesterday.

And there are too many issues on this. Search before posting crap.

**Comment by ycollet** [comment]
I just tested today and it wasn't working.
It's not necessary to be rude !

**Comment by bddenhartog** [comment]
@luisnabais Please avoid offensive or aggressive language within our organization's repositories.

@ycollet, please see #551.

**Comment by ycollet** [comment]
This was due to a problem with network connectivity with the fedy repo. Sorry for the noise.

**Comment by bddenhartog** [comment]
S3> This was due to a problem with network connectivity with the fedy repo. Sorry for the noise.

Our repositories are hosted on AWS S3, globally distributed behind Cloudfront (a CDN), and requests are load balanced to different CF distributions. It's very highly that the repositories were unavailable.

Until my comment, packages for F27 weren't actually deployed to the repositories.
