### ISSUE TITLE
failed to sync livna

### ISSUE THREAD

**Issue by stoc2528** [folkswithhats/fedy#554]
I get this on Fedora 27 trying to install libdvdcss or when doing dnf update.  " Failed to synchronize cache for repo 'livna', disabling. "

**Comment by bddenhartog** [comment]
The [`libdvdcss` plugin](https://github.com/folkswithhats/fedy/blob/master/plugins/libdvdcss.plugin/install.sh) simply installs the release RPM directly, which is what adds their repository to your system. It then installs the `libdvdcss` package, presumably from this repository.

That message usually relates to the host within the repository being unavailable - either because you are not able to communicate with it, or it is not responding.

When that happens, `dnf` issues this warning, effectively informing you that it is disabling the repository. This allows `dnf` to continue upgrading your system, skipping over the repository in question.

**Comment by bddenhartog** [comment]
On their repository's landing page (http://rpm.livna.org/), near the bottom they link to a list of mirrors to use and provide an example of how to install `libdvdcss` from them. This would be a one-time action and would not affect your local `/etc/yum.repos.d/livna.repo`.

**Comment by stoc2528** [comment]
Thanks, I've got lidbdvdcss now.
