### ISSUE TITLE
Fedy installs 64-bit gitkraken version on 32-bit system

### ISSUE THREAD

**Issue by sandstonegoblin** [folkswithhats/fedy#558]
Fedy installs 64bit gitkraken version (gitkraken-amd64.tar.gz) on a 32bit system.

Fedy 4.6.0
Fedora 27 32-bit

**Comment by bddenhartog** [comment]
Are you sure that they offer a 32-bit client? Fedy is just downloading the archive and unpacking it: https://github.com/folkswithhats/fedy/blob/master/plugins/gitkraken.plugin/install.sh

**Comment by sandstonegoblin** [comment]
No it seems only a 32 bit windows client is supported but no 32 bit linux client.

Nevertheless I would expect that it should not be possible (or without warning) to install incompatible packages with Fedy.

**Comment by bddenhartog** [comment]
> Nevertheless I would expect that it should not be possible to install incompatible packages with Fedy (or without warning).

You're right, and this was what I was going to lead to. Right now, we don't have a good story for categorizing plugins based on architecture, so there is no method for surfacing that information to the user. If we simply excluded showing plugins that didn't have applications supporting the user's architecture, we'd probably run into things like "where is X?" being created all the time -- so it's definitely an issue that needs a bit more thought given to it.

One potential solution would involve adding a new property to the metadata file for each plugin, something like `architectures`, a list of architectures supported by whatever application the plugin is installing. This could be used in the GUI to display compatibility information/warnings. If someone wanted to work on that, it would be appreciated!

I plan on rewriting the GUI in the future, where this won't really be an issue. For now, I'm going to close this issue because we don't really have a good solution for it.
