### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by giovannicaligaris** [folkswithhats/fedy#565]
Is there any way to add a progress bar or anything similar when the apps are installing or uninstalling?

**Comment by bddenhartog** [comment]
Since we're really just running shell scripts under the hood, which do a variety of things, there's not really any way to estimate how long each script would run - which prevents us from showing a progress bar with any relevant amount of accuracy at all.

At best, we could provide some kind of "in progress" state change, simply to provide more visual feedback than is currently given that installation/removal is in progress.

**Comment by giovannicaligaris** [comment]
This might be a very naive question.

If the installation script is composed of 3 commands, as an example

$ dnf -y install http://linuxdownload.adobe.com/adobe-release/adobe-release-$(uname -i)-1.0-1.noarch.rpm
$ rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
$ dnf -y install flash-plugin alsa-plugins-pulseaudio libcurl

Would it be possible to have a progress bar showing the completion of every command (every third).

I am not sure if it makes sense, so it would like something like this.

==== 
========
============
I found this online, I was wondering if there was any chance to apply it?

https://kimmobrunfeldt.github.io/progressbar.js/

As you can see, I am not a developer at all. Haha.

**Comment by bddenhartog** [comment]
@giovannicaligaris There's no real way that I'm aware of to get a progress bar on a non-streaming shell script. Because our scripts often download files and perform multiple actions, there's no way (without manually adding in "percentages" throughout each script) to determine how far along we are in the script's execution, or how long we have until the script is complete.

**Comment by bddenhartog** [comment]
I'm going to close this issue for now. If someone has a known method that could be easily implemented for determining script execution progress, I'm more than open to hearing about it.
